### ISSUE TITLE
Separate pdb folders

### ISSUE THREAD

**Issue by mpwaller** [ChristianOT/MasterNode#12]
We want to run this test suite many times in the future. 
So separate folders for 42 and 40 pdb files is not that bad of an idea. 

A groovy script might be very easy to write for this task.

hint: There is a book on your bookshelf for groovy.

**Comment by mpwaller** [comment]
any progress on this??

**Comment by ChristianOT** [comment]
I added a test script to separate. 
However i can't run the script from console, because no external groovy compiler is installed and i would need admin rights to install one.

But running the test in IntelliJ is working fine

**Comment by mpwaller** [comment]
where is the script??

**Comment by ChristianOT** [comment]
https://github.com/ChristianOT/MasterNode/blob/master/src/test/groovy/groovy/scripts/test.groovy

**Comment by mpwaller** [comment]
Well done
